### ISSUE TITLE
Problem notification

### ISSUE THREAD

**Issue by Desion321** [GentleMercenary/Onlyfans-notifications#1]
Hello, I noticed that the notifications do not notify when you receive a message, whereas before it did. I would like to say that the program is in its latest version and everything is good, just the message notifications which no longer work. Also, the program works when you buy a PPV you receive the notification

**Comment by GentleMercenary** [comment]
This has been known since June/July of this year. I don't really understand why OF stopped sending data about messages only without changing any of the other systems. I stopped actively looking for a solution a while ago and as far as I know no one else knows of a solution either.

**Comment by Desion321** [comment]
Today, I just noticed that the notifications for PPV in messages are working again, maybe OF changing something to make it work again.
