### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MadMan128989** [GentleMercenary/Onlyfans-notifications#3]
Can someone help me with how to fill those authentication header data in auth.json. Im so out
Thx

**Comment by MadMan128989** [comment]
@GentleMercenary

**Comment by GentleMercenary** [comment]
It's the same format used by [this scraper(https://github.com/UltimaHoarder/UltimaScraper). There's also [this extension](https://github.com/M-rcus/OnlyFans-Cookie-Helper) that allows you to simply copy and paste everything you need
