### ISSUE TITLE
Some error 

### ISSUE THREAD

**Issue by MadMan128989** [GentleMercenary/Onlyfans-notifications#5]
12:45:45 [INFO] Fetching user data
12:45:45 [ERROR] url: https://onlyfans.com/api2/v2/users/me, status 400 Bad Request, request body: {"error":{"code":301,"message":"Wrong user."}}
12:45:45 [ERROR] HTTP status client error (400 Bad Request) for url (https://onlyfans.com/api2/v2/users/me)
12:45:45 [INFO] Disconnected
Some1 can help what is the issue?

**Comment by GentleMercenary** [comment]
double-check to make sure the values in auth.json are still correct. If it still doesn't work try logging out and logging in again and changing the auth.json afterwards.

**Comment by MadMan128989** [comment]
Thank you i will try. Just felt wierd, happened overnight

**Comment by MadMan128989** [comment]
Cant get it to work anymore :/

**Comment by MadMan128989** [comment]
1 tried one more time, downloaded everything again, log out, in and still: 19:14:52 [INFO] Connecting
19:14:52 [INFO] Reading authentication parameters
19:14:52 [ERROR] Error reading auth data: Custom { kind: InvalidData, error: Error("control character (\\u0000-\\u001F) found while parsing a string", line: 3, column: 560) }
19:14:52 [ERROR] control character (\u0000-\u001F) found while parsing a string at line 3 column 560
19:14:52 [INFO] Disconnected
19:15:00 [INFO] Disconnecting
19:15:00 [INFO] Closing application
